# Generated by Django 2.2.11 on 2020-04-09 22:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addr', models.CharField(max_length=255, verbose_name='adresse')),
                ('phone', models.CharField(max_length=50, verbose_name='numéro de téléphone')),
            ],
            options={
                'verbose_name': 'adresse',
                'verbose_name_plural': 'adresses',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='users.Address'),
        ),
    ]
