# Generated by Django 2.2.12 on 2020-06-10 15:27

from django.db import migrations, models
import users.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200604_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(help_text='ville', max_length=64, verbose_name='ville'),
        ),
        migrations.AlterField(
            model_name='address',
            name='phone',
            field=users.fields.PhoneNumberField(help_text='numéro de téléphone', max_length=32, verbose_name='numéro de téléphone'),
        ),
        migrations.AlterField(
            model_name='address',
            name='postal_code',
            field=users.fields.MAPostalCodeField(blank=True, help_text='code postal', max_length=5, null=True, verbose_name='code postal'),
        ),
    ]
