# Generated by Django 2.2.12 on 2020-06-01 13:59

from django.db import migrations, models
import django.utils.crypto


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_auto_20200423_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='rnd',
            field=models.CharField(default=django.utils.crypto.get_random_string, max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('D', 'Delivered'), ('P', 'Pending'), ('R', 'Refund'), ('C', 'Canceled')], default='P', max_length=2),
        ),
    ]
