# Generated by Django 2.2.11 on 2020-06-02 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0004_auto_20200601_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('P', 'Paid'), ('D', 'Delivered'), ('O', 'Ongoing'), ('R', 'Refund'), ('C', 'Canceled')], default='O', max_length=2),
        ),
    ]
