# Generated by Django 2.2.11 on 2020-04-12 02:48

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='body',
            field=wagtail.core.fields.StreamField([('brands', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(help_text='ajouter un titre', label='titre')), ('brands', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(required=True)), ('text', wagtail.core.blocks.RichTextBlock(help_text='ajouter une paragraphe icei'))]), label='marques'))]))], blank=True, help_text='corps de page', null=True, verbose_name='corps'),
        ),
    ]
