# Generated by Django 2.2.11 on 2020-04-23 00:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20200423_0026'),
        ('wagtailimages', '0001_squashed_0021'),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carouselimages',
            name='brand_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='catalog.Brand'),
        ),
        migrations.AddField(
            model_name='carouselimages',
            name='logo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='carouselimages',
            name='text',
            field=models.CharField(max_length=100, null=True, verbose_name='Phrase pour la Marque'),
        ),
    ]
