# Generated by Django 2.2.12 on 2020-04-23 18:01

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20200423_0041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='body',
            field=wagtail.core.fields.StreamField([('brands', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(help_text='ajouter un titre', label='titre')), ('brands', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(help_text='Le titre', max_length=100, required=False)), ('image', wagtail.images.blocks.ImageChooserBlock(required=False)), ('text', wagtail.core.blocks.RichTextBlock(help_text='ajouter une paragraphe ici', required=False))]), label='Presentation'))])), ('connect', wagtail.core.blocks.StructBlock([('media_title', wagtail.core.blocks.CharBlock(help_text='le titre de paragraphe', max_length=60, required=True)), ('media_text', wagtail.core.blocks.RichTextBlock(features=['h2', 'h3', 'bold', 'italic', 'link'], help_text='le paragraphe de  medias sociaux partie', required=True)), ('newsletter_title', wagtail.core.blocks.CharBlock(help_text='le titre de NEWSLETTER', max_length=50, required=True)), ('newsletter_text', wagtail.core.blocks.RichTextBlock(features=['h2', 'h3', 'bold', 'italic', 'link'], help_text='le paragraphe de NEWSLETTER partie', required=True))]))], blank=True, help_text='corps de page', null=True, verbose_name='corps'),
        ),
    ]
