# Generated by Django 2.2.11 on 2020-03-30 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20200330_1820'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homepage',
            options={'verbose_name': "page d'accueil", 'verbose_name_plural': "pages d'accueil"},
        ),
    ]
