# Generated by Django 2.2.11 on 2020-03-30 23:20

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20200330_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='body',
            field=wagtail.core.fields.StreamField([('brands', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(help_text='ajouter un titre', label='titre')), ('brands', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(required=True)), ('titre', wagtail.core.blocks.CharBlock(max_length=100))]), label='marques'))]))], blank=True, null=True),
        ),
    ]
