# Generated by Django 2.2.11 on 2020-04-10 16:36

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.contrib.routable_page.models
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('wagtailimages', '0001_squashed_0021'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('group_title', models.CharField(max_length=100, null=True, verbose_name='titre de groupe')),
                ('body', wagtail.core.fields.StreamField([('connect', wagtail.core.blocks.StructBlock([('media_title', wagtail.core.blocks.CharBlock(help_text='le titre de paragraphe', max_length=60, required=True)), ('media_text', wagtail.core.blocks.RichTextBlock(features=['h2', 'h3', 'bold', 'italic', 'link'], help_text='le paragraphe de  medias sociaux partie', required=True)), ('newsletter_title', wagtail.core.blocks.CharBlock(help_text='le titre de NEWSLETTER', max_length=50, required=True)), ('newsletter_text', wagtail.core.blocks.RichTextBlock(features=['h2', 'h3', 'bold', 'italic', 'link'], help_text='le paragraphe de NEWSLETTER partie', required=True))])), ('paragraphe', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(help_text='le titre de paragraphe', max_length=50, required=True)), ('text', wagtail.core.blocks.RichTextBlock(features=['h2', 'h3', 'bold', 'italic', 'link'], help_text='le paragraphe de la marque', required=True)), ('image', wagtail.images.blocks.ImageChooserBlock(help_text='image', required=False))]))], blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Marque',
                'verbose_name_plural': 'Marques',
            },
            bases=(wagtail.contrib.routable_page.models.RoutablePageMixin, 'wagtailcore.page'),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('description', wagtail.core.fields.RichTextField(blank=True, null=True, verbose_name='description')),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='prix')),
                ('has_discount', models.BooleanField(default=False, verbose_name='a une remise ?')),
                ('discount_percent', models.PositiveSmallIntegerField(default=20, validators=[django.core.validators.MaxValueValidator(90)], verbose_name='pourcentage de remise')),
            ],
            options={
                'verbose_name': 'Produit',
                'verbose_name_plural': 'Produits',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ProductImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('product', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_images', to='catalog.Product')),
                ('product_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='extrat image pour produit')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GroupOfProducts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('brand', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_products', to='catalog.Brand')),
                ('group_product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='catalog.Product')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
            ],
            options={
                'verbose_name': 'Catégorie',
                'verbose_name_plural': 'Catégories',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='CarouselBrandImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('brand', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='carousel_images', to='catalog.Brand')),
                ('carousel_image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
