# Generated by Django 2.2.11 on 2020-04-23 00:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productrange',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ranges', to='catalog.Brand', verbose_name='marque'),
        ),
        migrations.AlterField(
            model_name='productrange',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ranges', to='catalog.Category', verbose_name='categorie'),
        ),
    ]
