# Generated by Django 2.2.11 on 2020-04-24 00:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20200423_0026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupofproducts',
            name='group_product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='catalog.Product'),
        ),
    ]
