# Generated by Django 2.2.11 on 2020-04-13 14:24

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20200413_1257'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attributeproduct',
            options={'ordering': ['sort_order']},
        ),
        migrations.RemoveField(
            model_name='product',
            name='attributes',
        ),
        migrations.AddField(
            model_name='attributeproduct',
            name='sort_order',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='attributeproduct',
            name='product',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='catalog.Product'),
        ),
        migrations.AlterField(
            model_name='attributeproduct',
            name='value',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='valeur'),
        ),
    ]
