# Generated by Django 2.2.11 on 2020-04-09 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_brand_best_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brand',
            old_name='best_title',
            new_name='group_title',
        ),
    ]
