# Generated by Django 2.2.11 on 2020-04-09 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20200409_2034'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BestOfProducts',
            new_name='GroupOfProducts',
        ),
    ]
