# Generated by Django 2.2.11 on 2020-04-09 20:41

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20200409_2035'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groupofproducts',
            old_name='carousel_product',
            new_name='group_product',
        ),
        migrations.AlterField(
            model_name='groupofproducts',
            name='brand',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_products', to='catalog.Brand'),
        ),
    ]
