# Generated by Django 2.2.12 on 2020-05-05 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20200426_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='productrange',
            name='slug',
            field=models.SlugField(max_length=200, unique=True),
        ),
    ]
