# Generated by Django 2.2.12 on 2020-05-10 01:23

from django.db import migrations, models
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20200505_2013'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ref',
            field=models.CharField(default='', max_length=50, verbose_name='code de référence'),
        ),
        migrations.AlterField(
            model_name='product',
            name='features',
            field=wagtail.core.fields.StreamField([('features', wagtail.core.blocks.ListBlock(wagtail.core.blocks.CharBlock(max_length=150, min_length=5), label='caractéristique'))], blank=True, help_text='caractéristiques du produit', null=True, verbose_name='caractéristique'),
        ),
    ]
