# Generated by Django 2.2.11 on 2020-04-09 22:30

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_brand_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='body',
            field=wagtail.core.fields.StreamField([('connect', wagtail.core.blocks.StructBlock([('Media_title', wagtail.core.blocks.CharBlock(help_text='le titre de paragraphe', max_length=60, required=True)), ('Media_text', wagtail.core.blocks.RichTextBlock(features=['h2', 'h3', 'bold', 'italic', 'link'], help_text='le paragraphe de  medias sociaux partie', required=True)), ('newsletter_title', wagtail.core.blocks.CharBlock(help_text='le titre de NEWSLETTER', max_length=50, required=True)), ('newsletter_text', wagtail.core.blocks.RichTextBlock(features=['h2', 'h3', 'bold', 'italic', 'link'], help_text='le paragraphe de NEWSLETTER partie', required=True))])), ('paragraphe', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(help_text='le titre de paragraphe', max_length=50, required=True)), ('text', wagtail.core.blocks.RichTextBlock(features=['h2', 'h3', 'bold', 'italic', 'link'], help_text='le paragraphe de la marque', required=True)), ('image', wagtail.images.blocks.ImageChooserBlock(help_text='image', required=False))]))], blank=True, null=True),
        ),
    ]
