# Generated by Django 2.2.12 on 2020-06-10 15:27

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_product_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='features',
            field=wagtail.core.fields.StreamField([('features', wagtail.core.blocks.ListBlock(wagtail.core.blocks.CharBlock(max_length=150, min_length=5), label='caractéristique')), ('badges', wagtail.core.blocks.ListBlock(wagtail.images.blocks.ImageChooserBlock(required=False), label='badge'))], blank=True, help_text='caractéristiques du produit', null=True, verbose_name='caractéristique'),
        ),
    ]
